### ISSUE TITLE
Tidying/polishing up

### ISSUE THREAD

**Issue by joshdavies14** [Joeyh021/SoftEng-Project#70]

**Comment by Joeyh021** [comment]
Dashboard pages are still missing a few bits:

- [x] Mentors overview of each mentee showing the things related to their relationship. 
  - [x] One to One meetings
  - [x] Plans of action
  - [x] Feedback
- [x] Mentor portal needs to show the mentee's names as well as their profile pictures
- [x] Group session stuff on mentor portal page needs rethinking as thats on it's own workshops page
- [ ] Colours need re-considering to meet contrast requirements
- [x] Mentee dashboard has no links to plans of action
- [x] Chat needs some polish and links to from dashboards

Also most of the buttons seem to do nothing so far so that probably wants fixing

**Comment by Joeyh021** [comment]
~~Also maybe want to make more use of notifications in some places?~~ Done

**Comment by Joeyh021** [comment]
~~Mentee Dashboard has no UI/functionality for selecting a mentor~~ Done
